export const fieldsConfig = [
  {
    name: "firstName",
    label: "First Name",
    type: "text",
    validation: { required: true, min: 2 },
  },
  {
    name: "lastName",
    label: "Last Name",
    type: "text",
    validation: { required: true, min: 2 },
  },
  {
    name: "email",
    label: "Email",
    type: "email",
    validation: { required: true },
  },
  {
    name: "age",
    label: "Age",
    type: "number",
    validation: { required: true, min: 16, max: 120 },
  },
  {
    name: "phone",
    label: "Phone",
    type: "tel",
    validation: { required: true, pattern: /^\d{10}$/ },
  },
  {
    name: "address",
    label: "Address",
    type: "text",
    validation: { required: true, min: 5 },
  },
  { name: "city", label: "City", type: "text", validation: { required: true } },
  {
    name: "state",
    label: "State",
    type: "text",
    validation: { required: true },
  },
  {
    name: "zip",
    label: "ZIP Code",
    type: "text",
    validation: { required: true, pattern: /^\d{5}$/ },
  },
  {
    name: "country",
    label: "Country",
    type: "text",
    validation: { required: true },
  },
  {
    name: "company",
    label: "Company",
    type: "text",
    validation: { required: false },
  },
  {
    name: "jobTitle",
    label: "Job Title",
    type: "text",
    validation: { required: false },
  },
  {
    name: "website",
    label: "Website",
    type: "url",
    validation: { required: false },
  },
  {
    name: "linkedin",
    label: "LinkedIn URL",
    type: "url",
    validation: { required: false },
  },
  {
    name: "github",
    label: "GitHub URL",
    type: "url",
    validation: { required: false },
  },
  {
    name: "password",
    label: "Password",
    type: "password",
    validation: { required: true, min: 6 },
  },
  {
    name: "confirmPwd",
    label: "Confirm Password",
    type: "password",
    validation: { required: true, matchField: "password" },
  },
  {
    name: "bio",
    label: "Bio",
    type: "textarea",
    validation: { required: false, max: 200 },
  },
  {
    name: "birthDate",
    label: "Birth Date",
    type: "date",
    validation: { required: true },
  },
  {
    name: "gender",
    label: "Gender",
    type: "select",
    options: ["Male", "Female"],
    validation: { required: true },
  },
];
